about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [

    path('about/', views.about, name='about'),

]

cart/urls.py
from django.urls import path, re_path
from . import views

app_name = 'cart'

urlpatterns = [
    path('detail/ ', views.cart_detail, name='cart_detail'),
    re_path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    re_path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

contact/urls.py
from django.urls import path

from . import views

app_name = 'contact'

urlpatterns = [

    path('contact/', views.contact, name='contact'),

]

my_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('cart/', include('cart.urls')),
    path('shop/', include('shop.urls')),
    path('about/', include('about.urls')),
    path('offers/', include('offers.urls')),
    path('contact/', include('contact.urls')),
    path('search/', include('search.urls')),
    path('orders/', include('orders.urls')),


    path('', TemplateView.as_view(template_name='home.html'), name='home')

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search/urls.py
from django.urls import path

from . import views

app_name = 'search'

urlpatterns = [

    path('search/', views.search, name='search'),

]

shop/urls.py
from django.urls import path, re_path

from . import views

app_name = 'shop'

urlpatterns = [

    path('list/', views.product_list, name='product_list'),
    re_path(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    re_path(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),




]

shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, unique=True, db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    stock = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)

    class Meta:
        ordering = ('name', )
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

    def get_stock(self):
        return self.stock

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from math import ceil
from cart.forms import CartAddProductForm




def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=category)

    context = {
        'category': category,
        'categories': categories,
        'products': products
    }
    return render(request, 'shop/product/list.html', context)


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    context = {
        'product': product,
        'cart_product_form': cart_product_form
    }
    return render(request, 'shop/product/detail.html', context)

shop/templates/shop/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}On-line Shop{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <style>
    #slider{
            overflow: hidden;
             height:400px;
             width:1347px;
       }

       #slider figure{
              position: relative;
              width: 500%;
              margin: 0;
              left:0;
              animation: 20s slider infinite;
       }

       #slider figure img{
              height:400px;
              width:1347px;
              float: left;
              background-size:cover;
       }

       @keyframes slider{
       0%{
            left: 0;
       }
       20%{
            left: 0;
       }
       25%{
             left: -100%;
       }
       45%{
             left: -100%;
       }
       50%{
              left: -200%;
       }
       70%{
               left: -200%;
       }
       75%{
                left: -300%;
       }
       95%{
                 left: -300%;
       }
       100%{
                 left: -400%;
       }
    }
.responsive {
  width: 100%;
  height: auto;
}
    </style>
</head>
<body>
{% include 'shop/navbar.html' %}

<div class="container">
    <div class="row" style="margin-top:5%">

         <button class="btn btn-info pull-right">
            {% with total_items=cart|length %}
                {% if cart|length > 0 %}

                    <a href="{% url "cart:cart_detail" %}" class="btn btn-info pull-right" style="color: #ffffff">My Orders :
                        {{ total_items }} item {{ total_items|pluralize }}, Rs. {{ cart.get_total_price }}
                    </a>
                    {% else %}

                    <a href="{% url "cart:cart_detail" %}" class="btn btn-info pull-right" style="color: #ffffff">Your cart is empty.</a>
                {% endif %}
            {% endwith %}
         </button>
    </div>
</div>
{% block content %}


{% endblock %}

<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
</body>
</html>

shop/templates/shop/imageslider.html
<html>
<head>

    <style type="text/css">

        #slider{
            overflow: hidden;
            height:1500px;
              width:4500px;

       }

       #slider figure{
              position: relative;
              width: 500%;
              margin: 0;
              left:0;
              animation: 20s slider infinite;
       }

       #slider figure img{
              height:1500px;
              width:4500px;
              float: left;
              background-size:cover;
       }

       @keyframes slider{
       0%{
            left: 0;
       }
       20%{
            left: 0;
       }
       25%{
             left: -100%;
       }
       45%{
             left: -100%;
       }
       50%{
              left: -200%;
       }
       70%{
               left: -200%;
       }
       75%{
                left: -300%;
       }
       95%{
                 left: -300%;
       }
       100%{
                 left: -400%;
       }
       }
    </style>
</head>
<body>
    <div id="slider">
        <figure>
            <img src="img/acer.jpg">
            <img src="img/fashion.jpg">
            <img src="img/pav1.jpg">
             <img src="img/noise-x3-banner.png">
            <img src="img/banner_nike.jpg">
            <img src="img/canon.jpg">
            <img src="img/backpack.png">
            <img src="img/jbl.png">
            <img src="img/galaxy-m30-banner.jpg">
            <img src="img/noise-x3-banner.png">
             <img src="img/MacBanner.jpg">
            <img src="img/noise-x5-banner.png">
            <img src="img/noise-x5-banner1.jpg">


        </figure>
    </div>
</body>
</html>

shop/templates/shop/navbar.html
{% load static %}
<nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="margin-bottom: 0px; background-color: #5AC8FA;">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="container-fluid">
      <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="{% url 'shop:product_list' %}" style="color: #ffffff">Shoppy Hub</a>




  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

    <ul class="nav navbar-nav navbar-right">

           <li>
          <form method='get' action="{% url 'search:search' %}" class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="search" id="search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
         </form>
           </li>

      <li class="dropdown">
          {% if request.user.is_authenticated %}
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="color: #ffffff">{{ request.user.username }}<b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li><a href="http://127.0.0.1:8000/search/search/?search=offer">Occasional and festive offers</a></li>
            <li><a href="{% url 'about:about' %}">About us</a></li>
            <li><a href="{% url 'contact:contact' %}">Contact us</a></li>
            <li><a href="{% url 'logout' %}">Logout</a></li>
             <li><a href="{% url 'password_reset' %}">Reset password</a></li>
            {% else %}
          <li class="divider"></li>
          <li><a href="{% url 'signup' %}">New to Shoppy Hub?</a></li>
        </ul>
         {% endif %}
      </li>
    </ul>
  </div><!-- /.navbar-collapse -->
  </div>
</nav>